### ISSUE TITLE
Reload(sys) issue

### ISSUE THREAD

**Issue by Zohaib261** [mclmza/linkedin-learning-downloader#77]
i am facing reload(sys) issue in lld.py on line number 13. What can i do?

**Comment by rpdelaney** [comment]
Run it with `python2`.

The script is in python2 but there is no shebang and the README does not specify a python version to run it with. On archlinux, for example, `python` is python3 whereas on other distros python is `python2`.

A shebang like `#!/usr/bin/env python2` should be added to `lld.py` and `config.py` should have its shebang updated to `#!/usr/bin/env python2` or at least `#!/usr/bin/python2`. While we are at it, the README should specify that users should install with `pip2` rather than `pip` and then run the script with `python2`, not `python`, both of which are ambiguous.

**Comment by yacsama** [comment]
Thanks, what I did was to install python 2.7 and run it as it is. it is faster
